name: Continuous Integration

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Use Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '18'

            - name: Install dependencies
              run: npm ci

            - name: Format
              run: npm run format

            - name: Run linter
              run: npm run lint

            - name: Run tests with coverage
              run: npm test -- --coverage

            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v3
              env:
                  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
                  fail_ci_if_error: true

            - name: Generate TypeDoc documentation
              run: npm run typedoc
